import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { ApolloClient, InMemoryCache } from '@apollo/client';
import { createHttpLink } from 'apollo-link-http';
import { setContext } from 'apollo-link-context';
import { gql } from '@apollo/client';
import { ApolloProvider } from 'react-apollo';
import { useState, useEffect } from 'react';


const httpLink = createHttpLink({ uri: 'https://test-shop-987.myshopify.com/api/2021-04/graphql.json' })

const middlewareLink = setContext(() => ({
  headers: {
    'X-Shopify-Storefront-Access-Token': 'c2a0a1dced98f06f472bc2ec933a0258'
  }
}))

const client = new ApolloClient({
  link: middlewareLink.concat(httpLink),
  cache: new InMemoryCache(),
})



export default function Home() {
  const [shopName, setShopName] = useState();

  useEffect(async () => {
     client.query({
      query: gql`
        query hello {
          shop {
            name
          }
        }
      `
    })
    .then(result => setShopName(result.data.shop.name));

  });

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          { shopName ? shopName : "loading..." }
        </h1>

        
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
